version: '3.9'

x-app: &default-app
  image: c18s/activemq
  network_mode: bridge
  restart: always
  environment:
    ACTIVEMQ_USER: admin
    ACTIVEMQ_PASSWORD: admin
  logging:
    driver: 'json-file'
    options:
      max-size: '100k'
      max-file: '1'

services:
  activemq-classic1:
    <<: *default-app
    container_name: activemq-classic1
    ports:
      - 8161:8161
      - 5671:5672
    volumes:
      - activemq1-volume:/opt/activemq/data
  activemq-classic2:
    <<: *default-app
    container_name: activemq-classic2
    ports:
      - 8162:8161
      - 5672:5672
    volumes:
      - activemq2-volume:/opt/activemq/data

volumes:
  activemq1-volume:
  activemq2-volume:
